name: Danger

on: [push]

jobs:
  danger:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 12.x
    - name: install yarn
      run: npm install -g yarn
    - name: yarn install
      run: |
        yarn install  --frozen-lockfile
    - name: Danger
      run: DEBUG="*" yarn danger ci --dangerfile ./.github/workflows/js/dangerfile.ts
      env:
        GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_TOKEN }}
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
