name: Danger

on: [pull_request]

jobs:
  danger:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Danger
      uses: danger/danger-js@9.1.6
      args: '--use-github-checks --dangerfile ./.github/workflows/js/dangerfile.ts'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
